version: '3.9'
services:
  db:
    image: mysql:8.0.29
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: docker
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: curso_spring_3
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - otavio-network
  curso-springboot:
    image: tav1nnn/curso-springboot3
    restart: always
    build: ./Curso-SpringBoot3
    working_dir: /Curso-SpringBoot3
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/curso_spring_3?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: 123
      SPRING.JPA.HIBERNATE.DDL-AUTO: none
    ports:
      - 80:80
    command:
      - mvn spring-boot:run
    depends_on:
      - db
    networks:
      - otavio-network
networks:
  otavio-network:
    driver: bridge